kind: pipeline
type: docker
name: default

steps:
  - name: build-backend
    image: node:20
    environment:
      DATABASE_URL:
        from_secret: db_url
    commands:
      - cd backend
      - npm ci
      - npm run build

  - name: build-frontend
    image: node:20
    commands:
      - cd frontend
      - npm ci
      - npm run build

  - name: dockerize
    image: plugins/docker
    settings:
      repo: your-dockerhub-username/habittracker
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
