version: '3.8'

services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-${PROJECT_NAME}
    restart: unless-stopped
    env_file:
      - ./.env
      - ./.env.local
    ports:
      - "${HTTP_PORT}:80"
    networks:
      - reactapp

networks:
  reactapp:
    name: reactapp-${PROJECT_NAME}