version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: vite-${PROJECT_NAME}
    ports:
      - "${HTTP_PORT_FRONT_DEV}:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: express-${PROJECT_NAME}
    ports:
      - "${HTTP_PORT_BACK_DEV}:5000"
    env_file:
      - .env
      - ./.env.local