version: '3.8'

services:
  react:
    image: node:18-alpine
    container_name: react-${PROJECT_NAME}-dev
    working_dir: /app
    env_file:
      - ./.env
      - ./.env.local
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "${HTTP_PORT_DEV}:5000"
    networks:
      - reactapp

networks:
  reactapp:
    name: reactapp-${PROJECT_NAME}-dev

